version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  laravel_network:

volumes:
  db_data:
