name: Build and Test

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "stagin" ]


env:
  PROJECT_ID: 'eminent-tesla-126408'
  REGION: 'us-central1'
  SERVICE: 'version-control-object'
  WORKLOAD_IDENTITY_PROVIDER: ${{secrets.WORKLOG_IDENTITY_PROVIDER}}

jobs:

  build:

    runs-on: ubuntu-latest
    #Build Docker image
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t vcapp .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name vcapp -e APP_NAME=vcapp -e APP_ENV=staging -e APP_KEY=${{secrets.APP_KEY}} -e APP_DEBUG=true -e APP_TIMEZONE=UTC -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=3306 -e DB_DATABASE=${{secrets.DB_DATABASE}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} vcapp

    - name: Install Composer dependencies
      run: docker exec vcapp composer install

    - name: Run database migrations
      run: docker exec vcapp php artisan migrate --force

    - name: Run tests with coverage
      run: docker exec vcapp php artisan test --coverage-text

